### ISSUE TITLE
Missing instructions for setting up upstream in getting_started.md

### ISSUE THREAD

**Issue by lauraschrwr** [pkeilbach/htwg-practical-nlp#181]
In the [getting_started.md](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/docs/getting_started.md) documentation, it seems that the instructions for adding the original repository as upstream may be missing. When working with a forked repository, the command to fetch updates from upstream didn’t work immediately for me.

It would be helpful to include a note explaining that if the repository is forked, users should first run the following command to set up the course repository as upstream before attempting to fetch updates:

`git remote add upstream https://github.com/pkeilbach/htwg-practical-nlp.git`

**Comment by pkeilbach** [comment]
@lauraschrwr I was under the assumption that the upstream is set automatically when you fork through the github web UI using the for button 🤔 

However, it could indeed be a useful note, so that students need to make sure to have set the correct upstream.

Would you want to add that to the guide?

I think the code box in line would be a good place

https://github.com/pkeilbach/htwg-practical-nlp/blob/20cb686f0a9c25efce79db4d60cd64a4025e879c/docs/getting_started.md?plain=1#L169

Maybe something like this:

```
# make sure you have the set the correct upstream repo
...

# if this is not the case, add the upstream
...

...
```

**Comment by lauraschrwr** [comment]
Yes, I can take over and add it to the guide
